spring:
  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

genres:
  cache:
    evict:
      cron:
        interval: 0 0 */4 * * *

movie:
  random:
    value: 3