spring:
  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

cache:
  evict:
    interval:
      genres: 14400000

movie:
  random:
    value: 3