spring:
  datasource:
    url: jdbc:postgresql://localhost:8200/cinema
    username: postgres
    password: postgres

application:
  jwtSecretKey: 2A462D4A614E635266556A586E3272357538782F413F4428472B4B6250655367
  jwTokenPrefix: Bearer
  jwTokenExpirationAfterHours: 24
